In [ ]:
#For tracking
from tracking_all_classes import ObjectTracking

tracker = ObjectTracking()
tracker()

inside Strongsort
using device:  cpu
Tracker = Strongsort


2023-07-26 22:18:57.766 | SUCCESS  | appearance.reid_model_factory:load_pretrained_weights:187 - Successfully loaded pretrained weights from "weights\osnet_x0_25_msmt17.pt"
2023-07-26 22:18:57.767 | WARNING  | appearance.reid_model_factory:load_pretrained_weights:191 - The following layers are discarded due to unmatched keys or layer size: ('classifier.weight', 'classifier.bias')


inside while



0: 480x640 4 cars, 292.1ms
Speed: 13.0ms preprocess, 292.1ms inference, 8.0ms postprocess per image at shape (1, 3, 640, 640)


[[    0.19805      361.89      290.25      491.42     0.91303           2]
 [     8.5538      527.59      1019.9       767.2      0.6178           2]
 [     411.93      377.21         462      419.06     0.50855           2]
 [     283.09      389.33      315.46      415.67     0.44227           2]]


inside while


0: 480x640 3 cars, 1 truck, 313.1ms
Speed: 14.0ms preprocess, 313.1ms inference, 5.3ms postprocess per image at shape (1, 3, 640, 640)


[[    0.19805      361.89      290.25      491.42     0.91303           2]
 [     8.5538      527.59      1019.9       767.2      0.6178           2]
 [     411.93      377.21         462      419.06     0.50855           2]
 [     283.09      389.33      315.46      415.67     0.44227           2]
 [     363.14      256.16      444.95      434.04     0.53729           7]
 [     80.988      376.13      141.49      402.82     0.39529           2]
 [     3.6734      516.78      1021.2      766.95     0.36676           2]
 [      209.5      380.98      243.73      395.96     0.27077           2]]


In [ ]:
import torch

import torchvision

if torch.cuda.is_available():
    print("CUDA is available!")
    print("CUDA version:", torch.version.cuda)
    print("Number of available GPUs:", torch.cuda.device_count())
    print("Current GPU device index:", torch.cuda.current_device())
    print("GPU name:", torch.cuda.get_device_name(torch.cuda.current_device()))
else:
    print("CUDA is not available.")

In [4]:
import yolo_detection

detection = yolo_detection()
detection()


0: 480x640 2 cars, 2 buss, 281.2ms
Speed: 15.1ms preprocess, 281.2ms inference, 4.5ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 car, 2 buss, 280.9ms
Speed: 13.5ms preprocess, 280.9ms inference, 5.5ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 bus, 397.3ms
Speed: 16.5ms preprocess, 397.3ms inference, 7.6ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 3 cars, 1 bus, 258.6ms
Speed: 14.8ms preprocess, 258.6ms inference, 5.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 5 cars, 1 bus, 1 truck, 251.9ms
Speed: 13.5ms preprocess, 251.9ms inference, 9.4ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 4 cars, 1 bus, 1 truck, 1 traffic light, 249.6ms
Speed: 13.0ms preprocess, 249.6ms inference, 5.6ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 3 cars, 1 bus, 1 traffic light, 265.1ms
Speed: 15.0ms preprocess, 265.1ms inference, 6.4ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 4 car

KeyboardInterrupt: 

In [2]:
import numpy as np
array_2d = np.zeros((2, 6))
print(array_2d)

[[          0           0           0           0           0           0]
 [          0           0           0           0           0           0]]
