In [4]:
#For tracking
from new_tracker import main

tracker = main()
tracker()

Model: osnet_x0_25
- params: 203,568
- flops: 82,316,000
Successfully loaded pretrained weights from "strong_sort/deep/checkpoint/osnet_x0_25_market1501.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']



0: 480x640 2 cars, 303.1ms
Speed: 17.6ms preprocess, 303.1ms inference, 6.0ms postprocess per image at shape (1, 3, 480, 640)


Results:  [[48, 384, 273, 474], [6, 522, 1010, 767]] [0.8717800974845886, 0.4495422840118408] [2, 2]


Output values:  []


0: 480x640 (no detections), 167.0ms
Speed: 10.0ms preprocess, 167.0ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)



Results:  [] [] []
Output values:  []


0: 480x640 (no detections), 170.2ms
Speed: 10.5ms preprocess, 170.2ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)



Results:  [] [] []
Output values:  []


0: 480x640 1 car, 2 traffic lights, 180.0ms
Speed: 12.0ms preprocess, 180.0ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)



Results:  [[2, 389, 1021, 767]] [0.2531008720397949] [2]
Output values:  []


0: 480x640 (no detections), 172.6ms
Speed: 8.5ms preprocess, 172.6ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 (no detections), 156.2ms


Results:  [] [] []
Output values:  []


Speed: 11.8ms preprocess, 156.2ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 3 traffic lights, 163.1ms


Results:  [] [] []
Output values:  []


Speed: 9.5ms preprocess, 163.1ms inference, 4.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 traffic light, 153.4ms


Results:  [] [] []
Output values:  []


Speed: 10.5ms preprocess, 153.4ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 bus, 1 traffic light, 157.3ms


Results:  [] [] []
Output values:  []


Speed: 11.0ms preprocess, 157.3ms inference, 3.8ms postprocess per image at shape (1, 3, 480, 640)



Results:  [[834, 265, 1023, 442]] [0.4937075674533844] [5]
Output values:  []


0: 480x640 1 potted plant, 150.9ms
Speed: 8.0ms preprocess, 150.9ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 potted plant, 143.1ms


Results:  [] [] []
Output values:  []


Speed: 10.5ms preprocess, 143.1ms inference, 3.5ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 car, 2 traffic lights, 1 bowl, 2 potted plants, 142.8ms
Speed: 9.5ms preprocess, 142.8ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)


Results:  [] [] []
Output values:  []
Results:  [[160, 394, 189, 406]] [0.2814316749572754] [2]



0: 480x640 1 car, 1 airplane, 1 traffic light, 149.1ms
Speed: 13.0ms preprocess, 149.1ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)


Output values:  []


Results:  [[196, 395, 224, 406]] [0.38037049770355225] [2]
Output values:  []


0: 480x640 1 car, 1 airplane, 1 bowl, 145.2ms
Speed: 9.4ms preprocess, 145.2ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)



Results:  [[228, 389, 254, 406]] [0.35221442580223083] [2]
Output values:  []


0: 480x640 1 car, 240.7ms
Speed: 14.7ms preprocess, 240.7ms inference, 6.0ms postprocess per image at shape (1, 3, 480, 640)



Results:  [[3, 384, 1008, 766]] [0.4870976209640503] [2]
Output values:  []


0: 480x640 2 cars, 2 traffic lights, 1 bowl, 225.0ms
Speed: 11.5ms preprocess, 225.0ms inference, 4.4ms postprocess per image at shape (1, 3, 480, 640)


Results:  [[4, 390, 1013, 766], [248, 399, 278, 413]] [0.42220741510391235, 0.3182026147842407] [2, 2]
Output values:  []



0: 480x640 4 cars, 1 traffic light, 1 fire hydrant, 2 potted plants, 220.4ms
Speed: 13.3ms preprocess, 220.4ms inference, 6.5ms postprocess per image at shape (1, 3, 480, 640)


Results:  [[115, 379, 146, 396], [267, 397, 305, 417], [115, 378, 168, 400], [2, 388, 1001, 766]] [0.3990011513233185, 0.3474831283092499, 0.2759951651096344, 0.2621006965637207] [2, 2, 2, 2]


Output values:  [[          3         388        1001         765           8           2      0.2621]]


0: 480x640 3 cars, 1 potted plant, 287.6ms
Speed: 16.0ms preprocess, 287.6ms inference, 5.0ms postprocess per image at shape (1, 3, 480, 640)


Results:  [[62, 412, 203, 464], [1, 524, 1019, 767], [163, 381, 188, 400]] [0.797976553440094, 0.4219030439853668, 0.33019185066223145] [2, 2, 2]


Output values:  [[          0         511        1023         767           8           2      0.4219]]


0: 480x640 2 cars, 1 potted plant, 275.5ms
Speed: 16.7ms preprocess, 275.5ms inference, 4.5ms postprocess per image at shape (1, 3, 480, 640)


Results:  [[0, 526, 1015, 767], [214, 375, 240, 395]] [0.5495119690895081, 0.4629206955432892] [2, 2]


Output values:  [[          2         526        1012         766           8           2     0.54951]]


0: 480x640 5 cars, 284.7ms
Speed: 20.8ms preprocess, 284.7ms inference, 3.4ms postprocess per image at shape (1, 3, 480, 640)


Results:  [[46, 407, 114, 450], [251, 381, 276, 400], [1, 508, 1019, 767], [1, 395, 1002, 766], [784, 391, 834, 429]] [0.6944198608398438, 0.6804911494255066, 0.5195897817611694, 0.5054629445075989, 0.27247318625450134] [2, 2, 2, 2, 2]



0: 480x640 (no detections), 161.7ms


Output values:  [[          9         510        1010         765           8           2     0.51959]]


Speed: 11.3ms preprocess, 161.7ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)



Results:  [] [] []
Output values:  [[         38         532         982         767           8           2     0.51959]]


0: 480x640 1 car, 156.6ms
Speed: 9.5ms preprocess, 156.6ms inference, 4.0ms postprocess per image at shape (1, 3, 480, 640)



Results:  [[278, 370, 314, 399]] [0.40797290205955505] [2]
Output values:  []


0: 480x640 2 cars, 154.2ms
Speed: 10.5ms preprocess, 154.2ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)



Results:  [[2, 524, 1012, 767], [280, 370, 316, 406]] [0.5753979682922363, 0.4909150302410126] [2, 2]
Output values:  [[          3         524        1010         766           8           2      0.5754]]


0: 480x640 2 cars, 184.4ms
Speed: 10.5ms preprocess, 184.4ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)



Results:  [[2, 520, 1019, 767], [267, 374, 317, 417]] [0.7424309253692627, 0.6461727619171143] [2, 2]
Output values:  [[          3         520        1017         766           8           2     0.74243]
 [        267         374         316         416          20           2     0.64617]]


0: 480x640 3 cars, 1 potted plant, 150.7ms
Speed: 8.5ms preprocess, 150.7ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 640)


Results:  [[224, 364, 314, 430], [0, 502, 1016, 767], [748, 389, 791, 425]] [0.6840659976005554, 0.5540672540664673, 0.29440468549728394] [2, 2, 2]
Output values:  [[          6         504        1009         765           8           2     0.55407]
 [        225         364         313         429          20           2     0.68407]]



0: 480x640 2 cars, 1 potted plant, 152.5ms
Speed: 8.3ms preprocess, 152.5ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)



Results:  [[116, 351, 296, 451], [3, 523, 1015, 766]] [0.8600201606750488, 0.6323121190071106] [2, 2]
Output values:  [[          0         522        1017         766           8           2     0.63231]
 [        116         351         295         450          20           2     0.86002]]


0: 480x640 1 car, 1 truck, 1 potted plant, 147.1ms
Speed: 11.5ms preprocess, 147.1ms inference, 3.3ms postprocess per image at shape (1, 3, 480, 640)


Results:  [[0, 326, 232, 520], [0, 325, 232, 520]] [0.6916438937187195, 0.28732457756996155] [2, 7]


Output values:  [[          7         530        1010         767           8           2     0.63231]
 [          6         330         228         515          20           2     0.69164]]


0: 480x640 1 car, 1 potted plant, 189.4ms
Speed: 11.3ms preprocess, 189.4ms inference, 4.0ms postprocess per image at shape (1, 3, 480, 640)



Results:  [[504, 384, 531, 405]] [0.2714579403400421] [2]
Output values:  [[          0         330         188         530          20           2     0.69164]]


0: 480x640 1 car, 1 potted plant, 190.8ms
Speed: 11.0ms preprocess, 190.8ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)



Results:  [[1, 524, 1012, 767]] [0.3749667704105377] [2]
Output values:  [[          3         524        1009         766           8           2     0.37497]]


0: 480x640 1 car, 1 potted plant, 180.4ms
Speed: 11.0ms preprocess, 180.4ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)



Results:  [[530, 389, 560, 407]] [0.27583688497543335] [2]
Output values:  [[          7         530        1005         767           8           2     0.37497]]


0: 480x640 2 cars, 193.7ms
Speed: 14.1ms preprocess, 193.7ms inference, 4.5ms postprocess per image at shape (1, 3, 480, 640)


Results:  [[530, 391, 571, 416], [435, 384, 449, 396]] [0.36011865735054016, 0.2748243510723114] [2, 2]
Output values:  []



0: 480x640 2 cars, 1 traffic light, 1 bench, 192.3ms
Speed: 15.1ms preprocess, 192.3ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 640)


Results:  [[2, 526, 1006, 767], [433, 380, 449, 393]] [0.5716877579689026, 0.2642393112182617] [2, 2]


Output values:  [[          2         526        1005         766           8           2     0.57169]]


0: 480x640 3 cars, 192.6ms
Speed: 10.0ms preprocess, 192.6ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)


Results:  [[2, 516, 1016, 767], [427, 373, 448, 390], [559, 384, 619, 421]] [0.4146476984024048, 0.4028783440589905, 0.2629651725292206] [2, 2, 2]


Output values:  [[          6         517        1010         765           8           2     0.41465]
 [        427         373         447         389          25           2     0.40288]]


0: 480x640 4 cars, 186.7ms
Speed: 10.5ms preprocess, 186.7ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)


Results:  [[572, 391, 657, 441], [4, 524, 1018, 767], [412, 379, 439, 397], [586, 399, 657, 441]] [0.5629124641418457, 0.555726170539856, 0.5004153251647949, 0.4265826940536499] [2, 2, 2, 2]
Output values:  [[          2         523        1018         767           8           2     0.55573]
 [        411         378         439         397          25           2     0.50042]]


In [ ]:
import torch

import torchvision

if torch.cuda.is_available():
    print("CUDA is available!")
    print("CUDA version:", torch.version.cuda)
    print("Number of available GPUs:", torch.cuda.device_count())
    print("Current GPU device index:", torch.cuda.current_device())
    print("GPU name:", torch.cuda.get_device_name(torch.cuda.current_device()))
else:
    print("CUDA is not available.")

In [4]:
import yolo_detection

detection = yolo_detection()
detection()


0: 480x640 1 vehicle, 635.5ms
Speed: 24.1ms preprocess, 635.5ms inference, 19.9ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 3 vehicles, 549.6ms
Speed: 15.0ms preprocess, 549.6ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 vehicle, 529.3ms
Speed: 14.1ms preprocess, 529.3ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 2 vehicles, 584.6ms
Speed: 15.1ms preprocess, 584.6ms inference, 2.5ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 vehicle, 551.6ms
Speed: 16.0ms preprocess, 551.6ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 vehicle, 321.7ms
Speed: 12.5ms preprocess, 321.7ms inference, 2.1ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 2 vehicles, 285.0ms
Speed: 13.5ms preprocess, 285.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 3 vehicles, 259.6ms
Speed: 10.5ms preprocess, 259.6ms inference, 1.0ms pos

TypeError: 'module' object is not callable

In [ ]:
 1: 'bicycle', 2: 'car', 3: 'motorcycle', 5: 'bus', 7: 'truck'